### ISSUE TITLE
Experiments avb_mnist_8_ac and avb_mnist_32_ac are the same

### ISSUE THREAD

**Issue by kirakowalska** [LMescheder/AdversarialVariationalBayes#5]
Hi, 

I have looked through the MNIST experiments and I have noticed that experiments 'avb_mnist_8_ac' and 'avb_mnist_32_ac' have exactly the same run.py scripts. Could you double check that the scripts are correct? When I try to modify one of them to have z-dim equal to 8 (instead of 32), I get the following error:

![image](https://user-images.githubusercontent.com/11439085/37102950-01ad97f0-2221-11e8-8e58-7c931f5ded08.png)

Many thanks!

**Comment by LMescheder** [comment]
Thanks, I fixed the latent dimension in the experiment scripts. Your second error happens because the script tries to load the model from an existing checkpoint. Just remove the `logs` folder to fix that problem.

**Comment by kirakowalska** [comment]
Thank you very much for the pointers and for fixing the scripts.
